{
  "id": "MAL-2024-4933",
  "summary": "Malicious code in coloramqs (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-COLORAMQS-6513406"
  ],
  "modified": "2024-06-28T03:14:50.725662Z",
  "published": "2024-06-25T13:33:44Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:33:44Z",
        "import_time": "2024-06-28T02:48:35.069895654Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-03713",
        "source": "reversing-labs",
        "sha256": "008bd471761148ad7cc9b12f32ddd09009644eeace6a8bc33fbd8dc0bc8e43dd"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-COLORAMQS-6513406"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "coloramqs",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/coloramqs"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/coloramqs/MAL-2024-4933.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}