{
  "id": "MAL-2024-6155",
  "summary": "Malicious code in tls-client-py (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "modified": "2024-06-25T13:43:43Z",
  "published": "2024-06-25T13:43:43Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:43:43Z",
        "import_time": "2024-06-28T02:51:02.817965577Z",
        "versions": [
          "1.0"
        ],
        "id": "RLMA-2024-04959",
        "source": "reversing-labs",
        "sha256": "b0066923a8c4316e3656576d53ab12b0dffc6eb94e40d0758b3d96506be5c5d3"
      }
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "tls-client-py",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/tls-client-py"
      },
      "versions": [
        "1.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/tls-client-py/MAL-2024-6155.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}