{
  "id": "MAL-2024-5688",
  "summary": "Malicious code in pycryptography (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-PYCRYPTOGRAPHY-5932162"
  ],
  "modified": "2024-06-28T03:15:06.022124Z",
  "published": "2024-06-25T13:39:51Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:39:51Z",
        "import_time": "2024-06-28T02:50:04.122914984Z",
        "versions": [
          "3.0.0",
          "1.0.0"
        ],
        "id": "RLMA-2024-04471",
        "source": "reversing-labs",
        "sha256": "83167a2fef23586192171e0a222c742a97a6cd85eed288075fe57e40b508111f"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCRYPTOGRAPHY-5932162"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "pycryptography",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/pycryptography"
      },
      "versions": [
        "3.0.0",
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pycryptography/MAL-2024-5688.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}