{
  "id": "MAL-2024-5726",
  "summary": "Malicious code in pyiopenssl (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "modified": "2024-06-25T13:40:13Z",
  "published": "2024-06-25T13:40:13Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:40:13Z",
        "import_time": "2024-06-28T02:50:09.437339118Z",
        "versions": [
          "20.0.7",
          "20.0.9",
          "20.0.12",
          "20.0.5",
          "20.0.8",
          "20.0.11",
          "20.0.6",
          "20.0.10"
        ],
        "id": "RLMA-2024-04515",
        "source": "reversing-labs",
        "sha256": "2198493e962d58dd319b208e96422fcdb46d9cf5a6e1761628d12123d5ed731a"
      }
    ]
  },
  "affected": [
    {
      "package": {
        "name": "pyiopenssl",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/pyiopenssl"
      },
      "versions": [
        "20.0.7",
        "20.0.9",
        "20.0.12",
        "20.0.5",
        "20.0.8",
        "20.0.11",
        "20.0.6",
        "20.0.10"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pyiopenssl/MAL-2024-5726.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}