{
  "id": "MAL-2024-5388",
  "summary": "Malicious code in myethertoolz (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "modified": "2024-06-25T13:37:26Z",
  "published": "2024-06-25T13:37:26Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:37:26Z",
        "import_time": "2024-06-28T02:49:28.784907826Z",
        "versions": [
          "1.0"
        ],
        "id": "RLMA-2024-04170",
        "source": "reversing-labs",
        "sha256": "abc1b6ae4613f0ff39ae1503ba2afa66a564e69278dd18194c369a1e92c34b6f"
      }
    ]
  },
  "affected": [
    {
      "package": {
        "name": "myethertoolz",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/myethertoolz"
      },
      "versions": [
        "1.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/myethertoolz/MAL-2024-5388.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}