{
  "id": "MAL-2024-6082",
  "summary": "Malicious code in syssqlite2toolsv2 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-SYSSQLITE2TOOLSV2-5932239"
  ],
  "modified": "2024-06-28T03:15:18.871074Z",
  "published": "2024-06-25T13:43:09Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:43:09Z",
        "import_time": "2024-06-28T02:50:54.112370543Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-04885",
        "source": "reversing-labs",
        "sha256": "9d95afe38c58478a5efa7d6e17d4abe0eb2ef3ae931e25e50b8415153c2d9524"
      }
    ]
  },
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-SYSSQLITE2TOOLSV2-5932239"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "syssqlite2toolsv2",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/syssqlite2toolsv2"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/syssqlite2toolsv2/MAL-2024-6082.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}