{
  "id": "MAL-2024-5832",
  "summary": "Malicious code in pytoolib (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "modified": "2024-06-25T13:41:08Z",
  "published": "2024-06-25T13:41:08Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:41:08Z",
        "import_time": "2024-06-28T02:50:22.988427284Z",
        "versions": [
          "0.7",
          "0.8",
          "0.9"
        ],
        "id": "RLMA-2024-04630",
        "source": "reversing-labs",
        "sha256": "9cc51b88acfcda3b09c263eedc91b7fde017f02c13e763b6d354c9a355bfd0f7"
      }
    ]
  },
  "affected": [
    {
      "package": {
        "name": "pytoolib",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/pytoolib"
      },
      "versions": [
        "0.7",
        "0.8",
        "0.9"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pytoolib/MAL-2024-5832.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}